# Generated by Django 5.2.17 on 2026-09-14 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_check_in_time_reservation_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_check_in_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='board',
            name='default_check_out_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
