# Generated by Django 5.2.17 on 2026-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_board_default_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_date_to_after_date_from',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='reservation_date_to_after_date_from'),
        ),
    ]
