# Generated by Django 5.2.17 on 2026-09-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_reservation_date_to_after_date_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('id_card', 'ID card'), ('drivers_license', "Driver's license")], max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='residence_building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='residence_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='residence_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='residence_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='residence_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='visa_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
