# Generated by Django 5.2.17 on 2026-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_guest_options_remove_guest_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='notes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_housekeeping',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_kitchen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_reception',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_system',
            field=models.TextField(blank=True),
        ),
    ]
