# Generated by Django 5.2.17 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='linked_reservations',
            field=models.ManyToManyField(blank=True, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_general',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_parking',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out')], default='confirmed', max_length=20),
        ),
    ]
