# Generated by Django 5.2.17 on 2026-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_linked_reservations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
