# Generated by Django 5.2.17 on 2026-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reservations', '0008_alter_board_options_board_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='accounts.hotel'),
        ),
    ]
