# Generated by Django 5.2.17 on 2026-09-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reservations', '0009_board_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='accounts.hotel'),
        ),
    ]
