# Generated by Django 5.2.17 on 2026-09-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_board_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
